on: push
name: 🚀 Upload threejs dependency
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@main
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: h2870922.stratoserver.net
        username: u2870922
        password: ${{ secrets.ZAUBARTOURS_FTP_PASSWORD }}
        server-dir: /htdocs/testing/components/
